#! /bin/sh
HILDON_DESKTOP_DIR=$HOME/.config/hildon-desktop
HOME_USER_PLUGINS=$HILDON_DESKTOP_DIR/home.plugins
HOME_USER_PLUGINS_BACKUP=$HOME_USER_PLUGINS-backup

if [ -f "$HOME_USER_PLUGINS_BACKUP" ] ; then
  mv -f "$HOME_USER_PLUGINS_BACKUP" "$HOME_USER_PLUGINS"
fi
